[package]
authors = ["Austin Bonander <austin.bonander@gmail.com>"]
name = "wingui"
version = "0.1.0"
build = "gen_system_class_defs.rs"

[dependencies]
kernel32-sys = "0.1"
lazy_static = "0.1.15"
log = "0.3.4"
user32-sys = "0.1"
winapi = "0.2"
