[package]
name = "wingui"
version = "0.1.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

[dependencies]
encoding_literals = "0.1"
lazy_static = "0.1"
winapi = "0.2"
user32-sys = "0.1"
kernel32-sys = "0.1"
